export const Types = {
  USER_SERVICE: Symbol.for("USER_SERVICE"),
  USER_REPOSITORY: Symbol.for("USER_REPOSITORY"),
  USER_CONTROLLER: Symbol.for("USER_CONTROLLER"),

  TODO_SERVICE: Symbol.for("TODO_SERVICE"),
  TODO_REPOSITORY: Symbol.for("TODO_REPOSITORY"),
  TODO_CONTROLLER: Symbol.for("TODO_CONTROLLER"),

  USER_TABLE: Symbol.for("USER_TABLE"),
  TODO_LIST_TABLE: Symbol.for("TODO_LIST_TABLE"),
};
