export const Types = {
  USER_SERVICE: Symbol.for("USER_SERVICE"),
  USER_REPOSITORY: Symbol.for("USER_REPOSITORY"),
  USER_CONTROLLER: Symbol.for("USER_CONTROLLER"),

  TODO_LIST_SERVICE: Symbol.for("TODO_LIST_SERVICE"),
  TODO_LIST_REPOSITORY: Symbol.for("TODO_LIST_REPOSITORY"),
  TODO_LIST_CONTROLLER: Symbol.for("TODO_LIST_CONTROLLER"),

  USER_TABLE: Symbol.for("USER_TABLE"),
};
